# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    container_name: finboard_web
    restart: unless-stopped
    volumes:
      - staticfiles_volume:/app/staticfiles
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env

volumes:
  staticfiles_volume: