# Generated by Django 5.2.4 on 2025-08-06 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Ex: PETR4, WDOFUT, EURUSD', max_length=20, unique=True, verbose_name='Ticker')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('market', models.CharField(choices=[('B3_ACOES', 'B3 - Ações'), ('B3_FUTUROS', 'B3 - Mercado Futuro'), ('FOREX_PARES', 'Forex - Pares de Moedas'), ('FOREX_COMMODITIES', 'Forex - Commodities'), ('FOREX_INDICES', 'Forex - Índices')], max_length=20, verbose_name='Mercado')),
                ('currency', models.CharField(choices=[('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano')], max_length=3, verbose_name='Moeda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Estratégia')),
                ('description', models.TextField(verbose_name='Descrição do Setup')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10, verbose_name='Status')),
                ('initial_operation_type', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10, verbose_name='Tipo da Operação Inicial')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('net_financial_result', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Resultado Financeiro Líquido')),
                ('points_pips_result', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Resultado em Pontos/Pips')),
                ('entry_reason', models.TextField(verbose_name='Motivo da Entrada')),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais (Lições Aprendidas)')),
                ('entry_sentiment', models.CharField(blank=True, choices=[('CONFIANTE', 'Confiante'), ('ANSIOSO', 'Ansioso'), ('COM_MEDO', 'Com Medo'), ('FOCADO', 'Focado'), ('EFORICO', 'Eufórico')], max_length=10, null=True, verbose_name='Sentimento na Entrada')),
                ('execution_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualidade da Execução (1-5)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.asset', verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.strategy', verbose_name='Estratégia')),
                ('tags', models.ManyToManyField(blank=True, to='dashboard.tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('datetime', models.DateTimeField(verbose_name='Data e Hora')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Preço')),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custos')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dashboard.operation', verbose_name='Operação')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='trade_attachments/', verbose_name='Arquivo')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.operation', verbose_name='Operação')),
            ],
        ),
    ]
