# Generated by Django 5.2.4 on 2025-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='initial_stop_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Preço de Stop Planejado'),
        ),
        migrations.AddField(
            model_name='operation',
            name='initial_target_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Preço de Alvo Planejado'),
        ),
    ]
