# Generated by Django 5.2.4 on 2025-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_operation_initial_stop_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade'),
        ),
    ]
